//
//  LanguageManager.swift
//  thunder
//
//  Created by Carlos Felipe Araújo on 14/05/26.
//

import Combine
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case ptBR = "pt-BR"
    case en
    case es

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .ptBR: return "Português (Brasil)"
        case .en: return "English"
        case .es: return "Español"
        }
    }
}

class LanguageManager: ObservableObject {
    @Published var currentLanguage: AppLanguage {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "appLanguage")
            // Update global system preference for this app
            UserDefaults.standard.set([currentLanguage.rawValue], forKey: "AppleLanguages")
        }
    }

    static let shared = LanguageManager()

    private init() {
        let saved = UserDefaults.standard.string(forKey: "appLanguage") ?? AppLanguage.ptBR.rawValue
        currentLanguage = AppLanguage(rawValue: saved) ?? .ptBR
    }

    func local(_ key: String) -> String {
        return Translations.getText(key, for: currentLanguage)
    }
}

enum Translations {
    static func getText(_ key: String, for lang: AppLanguage) -> String {
        let dict: [String: [AppLanguage: String]] = [
            "settings": [.ptBR: "Configurações", .en: "Settings"],
            "sidebar": [.ptBR: "Barra Lateral", .en: "Sidebar"],
            "general": [.ptBR: "Geral", .en: "General"],
            "language": [.ptBR: "Idioma", .en: "Language"],
            "larger_folder_icons": [.ptBR: "Ícones de pastas maiores", .en: "Larger folder icons"],
            "about_thunder": [.ptBR: "Sobre o Thunder", .en: "About Thunder"],
            "favorites": [.ptBR: "Favoritos", .en: "Favorites"],
            "devices": [.ptBR: "Dispositivos", .en: "Devices"],
            "tags": [.ptBR: "Etiquetas", .en: "Tags"],
            "tag": [.ptBR: "Etiqueta", .en: "Tag"],
            "show_items_sidebar": [.ptBR: "Mostrar estes itens na barra lateral:", .en: "Show these items in the sidebar:"],
            "sections": [.ptBR: "Seções:", .en: "Sections:"],
            "by": [.ptBR: "Por", .en: "By"],
            "locations": [.ptBR: "Locais", .en: "Locations"],
            "open": [.ptBR: "Abrir", .en: "Open"],
            "eject": [.ptBR: "Ejetar", .en: "Eject"],
            "remove_favorites": [.ptBR: "Remover dos Favoritos", .en: "Remove from Favorites"],
            "home": [.ptBR: "Início", .en: "Home"],
            "desktop": [.ptBR: "Área de Trabalho", .en: "Desktop"],
            "documents": [.ptBR: "Documentos", .en: "Documents"],
            "movies": [.ptBR: "Filmes", .en: "Movies"],
            "pictures": [.ptBR: "Imagens", .en: "Pictures"],
            "music": [.ptBR: "Música", .en: "Music"],
            "downloads": [.ptBR: "Downloads", .en: "Downloads"],
            "applications": [.ptBR: "Aplicativos", .en: "Applications"],
            "trash": [.ptBR: "Lixeira", .en: "Trash"],
            "app_description": [
                .ptBR: "Inspirado no Thunar do XFCE, sem qualquer vínculo com o projeto original.",
                .en: "Inspired by XFCE's Thunar, with no affiliation to the original project.",
            ],
            "red": [.ptBR: "Vermelho", .en: "Red"],
            "orange": [.ptBR: "Laranja", .en: "Orange"],
            "yellow": [.ptBR: "Amarelo", .en: "Yellow"],
            "green": [.ptBR: "Verde", .en: "Green"],
            "blue": [.ptBR: "Azul", .en: "Blue"],
            "purple": [.ptBR: "Roxo", .en: "Purple"],
            "gray": [.ptBR: "Cinza", .en: "Gray"],
            "free_of": [.ptBR: "%@ livre de %@", .en: "%@ free of %@"],
            "remove_all": [.ptBR: "Remover Todas", .en: "Remove All"],
            "search_placeholder": [.ptBR: "Buscar", .en: "Search"],
            "rename": [.ptBR: "Renomear", .en: "Rename"],
            "get_info": [.ptBR: "Obter Informações", .en: "Get Info"],
            "open_terminal": [.ptBR: "Abrir no Terminal", .en: "Open in Terminal"],
            "add_favorites": [.ptBR: "Adicionar aos Favoritos", .en: "Add to Favorites"],
            "copy": [.ptBR: "Copiar", .en: "Copy"],
            "cut": [.ptBR: "Recortar", .en: "Cut"],
            "paste": [.ptBR: "Colar", .en: "Paste"],
            "compress": [.ptBR: "Comprimir", .en: "Compress"],
            "move_to_trash": [.ptBR: "Mover para Lixeira", .en: "Move to Trash"],
            "delete_permanently": [.ptBR: "Excluir Permanentemente", .en: "Delete Permanently"],
            "cancel": [.ptBR: "Cancelar", .en: "Cancel"],
            "delete": [.ptBR: "Excluir", .en: "Delete"],
            "new_folder": [.ptBR: "Nova Pasta", .en: "New Folder"],
            "new_file": [.ptBR: "Novo Arquivo", .en: "New File"],
            "search_results_in": [.ptBR: "Resultados em", .en: "Results in"],
            "no_items_found": [.ptBR: "Nenhum item encontrado", .en: "No items found"],
            "try_searching_again": [.ptBR: "Tente buscar por outro nome.", .en: "Try searching for another name."],
            "error": [.ptBR: "Erro", .en: "Error"],
            "hide_hidden": [.ptBR: "Ocultar arquivos ocultos", .en: "Hide hidden files"],
            "show_hidden": [.ptBR: "Mostrar arquivos ocultos", .en: "Show hidden files"],
            "confirm_delete": [.ptBR: "Excluir Permanentemente", .en: "Delete Permanently"],
            "delete_warning_singular": [.ptBR: "'%@' será apagado definitivamente. Esta ação não pode ser desfeita.", .en: "'%@' will be permanently deleted. This action cannot be undone."],
            "delete_warning_plural": [.ptBR: "%d itens serão apagados definitivamente. Esta ação não pode ser desfeita.", .en: "%d items will be permanently deleted. This action cannot be undone."],
            "name": [.ptBR: "Nome", .en: "Name"],
            "date": [.ptBR: "Data", .en: "Date"],
            "size": [.ptBR: "Tamanho", .en: "Size"],
            "item_count_singular": [.ptBR: "item", .en: "item"],
            "item_count_plural": [.ptBR: "itens", .en: "items"],
            "searching": [.ptBR: "Buscando", .en: "Searching"],
            "searching_query": [.ptBR: "Buscando \"%@\"...", .en: "Searching \"%@\"..."],
            "searching_tag": [.ptBR: "Buscando itens com etiqueta \"%@\"...", .en: "Searching items with tag \"%@\"..."],
            "volume_unmounted": [.ptBR: "Volume \"%@\" foi desmontado", .en: "Volume \"%@\" was unmounted"],
            "item_exists": [.ptBR: "Já existe um item com o nome \"%@\" neste local.", .en: "An item named \"%@\" already exists here."],
            "create_folder_error": [.ptBR: "Erro ao criar pasta: %@", .en: "Error creating folder: %@"],
            "create_file_error": [.ptBR: "Não foi possível criar o arquivo.", .en: "Could not create file."],
            "moved_to_trash_singular": [.ptBR: "\"%@\" movido para a Lixeira", .en: "\"%@\" moved to Trash"],
            "moved_to_trash_plural": [.ptBR: "%d itens movidos para a Lixeira", .en: "%d items moved to Trash"],
            "deleted_perm_singular": [.ptBR: "\"%@\" excluído permanentemente", .en: "\"%@\" permanently deleted"],
            "deleted_perm_plural": [.ptBR: "%d itens excluídos permanentemente", .en: "%d items permanently deleted"],
            "compressing": [.ptBR: "Comprimindo \"%@\"...", .en: "Compressing \"%@\"..."],
            "compress_success": [.ptBR: "\"%@\" comprimido com sucesso", .en: "\"%@\" compressed successfully"],
            "archive_name": [.ptBR: "Nome do Arquivo", .en: "Archive Name"],
            "format": [.ptBR: "Formato", .en: "Format"],
            "compress_items": [.ptBR: "Comprimir Itens", .en: "Compress Items"],
            "extracting": [.ptBR: "Descompactando \"%@\"...", .en: "Extracting \"%@\"..."],
            "extract_success": [.ptBR: "\"%@\" descompactado com sucesso", .en: "\"%@\" extracted successfully"],
            "renamed_to": [.ptBR: "\"%@\" renomeado para \"%@\"", .en: "\"%@\" renamed to \"%@\""],
            "copied_singular": [.ptBR: "\"%@\" copiado", .en: "\"%@\" copied"],
            "copied_plural": [.ptBR: "%d itens copiados", .en: "%d items copied"],
            "cut_singular": [.ptBR: "\"%@\" recortado", .en: "\"%@\" cut"],
            "cut_plural": [.ptBR: "%d itens recortados", .en: "%d items cut"],
            "pasting": [.ptBR: "Colando", .en: "Pasting"],
            "moving": [.ptBR: "Movendo", .en: "Moving"],
            "pasting_singular": [.ptBR: "%@ \"%@\"...", .en: "%@ \"%@\"..."],
            "pasting_plural": [.ptBR: "%@ %d itens...", .en: "%@ %d items..."],
            "paste_success_singular": [.ptBR: "\"%@\" %@ com sucesso", .en: "\"%@\" %@ successfully"],
            "paste_success_plural": [.ptBR: "%d itens %@s com sucesso", .en: "%d items %@ successfully"],
            "no_tag_results": [.ptBR: "Nenhum item encontrado com esta etiqueta", .en: "No items found with this tag"],
            "tag_added_singular": [.ptBR: "Etiqueta \"%@\" adicionada a \"%@\"", .en: "Tag \"%@\" added to \"%@\""],
            "tag_added_plural": [.ptBR: "Etiqueta \"%@\" adicionada a %d itens", .en: "Tag \"%@\" added to %d items"],
            "tag_removed_singular": [.ptBR: "Etiqueta \"%@\" removida de \"%@\"", .en: "Tag \"%@\" removed from \"%@\""],
            "tag_removed_plural": [.ptBR: "Etiqueta \"%@\" removida de %d itens", .en: "Tag \"%@\" removed from %d items"],
            "all_tags_removed_singular": [.ptBR: "Etiquetas removidas de \"%@\"", .en: "Tags removed from \"%@\""],
            "all_tags_removed_plural": [.ptBR: "Etiquetas removidas de %d itens", .en: "Tags removed from %d items"],
            "added_to_favorites": [.ptBR: "\"%@\" adicionado aos Favoritos", .en: "\"%@\" added to Favorites"],
            "removed_from_favorites": [.ptBR: "\"%@\" removido dos Favoritos", .en: "\"%@\" removed from Favorites"],
            "no_items_found_for": [.ptBR: "Nenhum item encontrado para \"%@\"", .en: "No items found for \"%@\""],
            "create": [.ptBR: "Criar", .en: "Create"],
            "error_deleting_item": [.ptBR: "Erro ao excluir: %@", .en: "Error deleting: %@"],
            "pasted": [.ptBR: "colado", .en: "pasted"],
            "moved": [.ptBR: "movido", .en: "moved"],
            "folder_name_placeholder": [.ptBR: "Nome da pasta", .en: "Folder name"],
            "file_name_placeholder": [.ptBR: "Nome do arquivo", .en: "File name"],
            "new_name_placeholder": [.ptBR: "Novo nome", .en: "New name"],
            "location": [.ptBR: "Local", .en: "Where"],
            "created": [.ptBR: "Criado", .en: "Created"],
            "modified": [.ptBR: "Modificado", .en: "Modified"],
            "dimensions": [.ptBR: "Dimensões", .en: "Dimensions"],
            "full_path": [.ptBR: "Caminho completo", .en: "Full path"],
            "contents": [.ptBR: "Conteúdo", .en: "Contents"],
            "close": [.ptBR: "Fechar", .en: "Close"],
            "folder": [.ptBR: "Pasta", .en: "Folder"],
            "file": [.ptBR: "Arquivo", .en: "File"],
            "calculating": [.ptBR: "Calculando...", .en: "Calculating..."],
            "ok": [.ptBR: "OK", .en: "OK"],
            "access_denied_title": [.ptBR: "Acesso Negado (Proteção do macOS)", .en: "Access Denied (macOS Protection)"],
            "access_denied_message": [
                .ptBR: "Para acessar a Lixeira ou pastas protegidas do sistema, vá em:\nAjustes do Sistema > Privacidade e Segurança > Acesso Total ao Disco\ne conceda permissão para o seu aplicativo (ou para o Xcode/Terminal).",
                .en: "To access the Trash or protected system folders, go to:\nSystem Settings > Privacy & Security > Full Disk Access\nand grant permission to your application (or to Xcode/Terminal).",
            ],
            "access_error_generic": [.ptBR: "Não foi possível acessar a pasta.\nDetalhes: %@", .en: "Could not access folder.\nDetails: %@"],
            "replace": [.ptBR: "Substituir", .en: "Replace"],
            "keep_both": [.ptBR: "Manter Ambos", .en: "Keep Both"],
            "skip": [.ptBR: "Ignorar", .en: "Skip"],
            "item_exists_title": [.ptBR: "Item já existe", .en: "Item already exists"],
            "item_exists_message": [.ptBR: "Um item com o nome \"%@\" já existe neste local. O que você deseja fazer?", .en: "An item named \"%@\" already exists in this location. What do you want to do?"],
            "rotate": [.ptBR: "Rotacionar", .en: "Rotate"],
            "resize": [.ptBR: "Redimensionar", .en: "Resize"],
            "rotate_image": [.ptBR: "Rotacionar Imagem", .en: "Rotate Image"],
            "resize_image": [.ptBR: "Redimensionar Imagem", .en: "Resize Image"],
            "rotation_angle": [.ptBR: "Ângulo de Rotação", .en: "Rotation Angle"],
            "width": [.ptBR: "Largura", .en: "Width"],
            "height": [.ptBR: "Altura", .en: "Height"],
            "maintain_aspect_ratio": [.ptBR: "Manter proporção", .en: "Maintain aspect ratio"],
            "apply": [.ptBR: "Aplicar", .en: "Apply"],
            "percent": [.ptBR: "Porcentagem", .en: "Percent"],
            "edit_dimension": [.ptBR: "Dimensão base", .en: "Base dimension"],
            "save_as_copy": [.ptBR: "Salvar como cópia", .en: "Save as copy"],
            "name_label": [.ptBR: "Nome", .en: "Name"],
            "extension_label": [.ptBR: "Extensão", .en: "Extension"],
            "extension_warning": [.ptBR: "Alterar a extensão pode tornar o arquivo ilegível.", .en: "Changing the extension might make the file unreadable."],
            "unlock_extension_help": [.ptBR: "Desbloquear extensão para edição", .en: "Unlock extension for editing"],
            "lock_extension_help": [.ptBR: "Bloquear extensão", .en: "Lock extension"],
            "uppercase": [.ptBR: "TUDO MAIÚSCULO", .en: "UPPERCASE"],
            "lowercase": [.ptBR: "tudo minúsculo", .en: "lowercase"],
            "capitalize": [.ptBR: "Primeira Letra Maiúscula", .en: "Capitalize"],
            "text_case_help": [.ptBR: "Alterar maiúsculas/minúsculas", .en: "Change text case"],
            "moved_singular": [.ptBR: "\"%@\" movido para \"%@\"", .en: "\"%@\" moved to \"%@\""],
            "moved_plural": [.ptBR: "%d itens movidos para \"%@\"", .en: "%d items moved to \"%@\""],
            "storage": [.ptBR: "Armazenamento", .en: "Storage"],
            "storage_macintosh_hd": [.ptBR: "Macintosh HD", .en: "Macintosh HD"],
            "storage_total": [.ptBR: "Capacidade total", .en: "Total capacity"],
            "storage_used": [.ptBR: "Utilizado", .en: "Used"],
            "storage_free": [.ptBR: "Disponível", .en: "Available"],
            "storage_unavailable": [.ptBR: "Informações de armazenamento indisponíveis", .en: "Storage information unavailable"],
        ]

        let spanish: [String: String] = [
            "settings": "Configuración",
            "sidebar": "Barra lateral",
            "general": "General",
            "language": "Idioma",
            "larger_folder_icons": "Iconos de carpetas más grandes",
            "about_thunder": "Acerca de Thunder",
            "favorites": "Favoritos",
            "devices": "Dispositivos",
            "tags": "Etiquetas",
            "tag": "Etiqueta",
            "show_items_sidebar": "Mostrar estos elementos en la barra lateral:",
            "sections": "Secciones:",
            "by": "Por",
            "locations": "Ubicaciones",
            "open": "Abrir",
            "eject": "Expulsar",
            "remove_favorites": "Eliminar de favoritos",
            "home": "Inicio",
            "desktop": "Escritorio",
            "documents": "Documentos",
            "movies": "Películas",
            "pictures": "Imágenes",
            "music": "Música",
            "downloads": "Descargas",
            "applications": "Aplicaciones",
            "trash": "Papelera",
            "app_description": "Inspirado en Thunar de XFCE, sin ninguna relación con el proyecto original.",
            "red": "Rojo",
            "orange": "Naranja",
            "yellow": "Amarillo",
            "green": "Verde",
            "blue": "Azul",
            "purple": "Morado",
            "gray": "Gris",
            "free_of": "%@ libre de %@",
            "remove_all": "Eliminar todas",
            "search_placeholder": "Buscar",
            "rename": "Renombrar",
            "get_info": "Obtener información",
            "open_terminal": "Abrir en Terminal",
            "add_favorites": "Añadir a favoritos",
            "copy": "Copiar",
            "cut": "Cortar",
            "paste": "Pegar",
            "compress": "Comprimir",
            "move_to_trash": "Mover a la papelera",
            "delete_permanently": "Eliminar permanentemente",
            "cancel": "Cancelar",
            "delete": "Eliminar",
            "new_folder": "Nueva carpeta",
            "new_file": "Nuevo archivo",
            "search_results_in": "Resultados en",
            "no_items_found": "No se encontraron elementos",
            "try_searching_again": "Intenta buscar otro nombre.",
            "error": "Error",
            "hide_hidden": "Ocultar archivos ocultos",
            "show_hidden": "Mostrar archivos ocultos",
            "confirm_delete": "Eliminar permanentemente",
            "delete_warning_singular": "'%@' se eliminará permanentemente. Esta acción no se puede deshacer.",
            "delete_warning_plural": "%d elementos se eliminarán permanentemente. Esta acción no se puede deshacer.",
            "name": "Nombre",
            "date": "Fecha",
            "size": "Tamaño",
            "item_count_singular": "elemento",
            "item_count_plural": "elementos",
            "searching": "Buscando",
            "searching_query": "Buscando \"%@\"...",
            "searching_tag": "Buscando elementos con la etiqueta \"%@\"...",
            "volume_unmounted": "El volumen \"%@\" fue desmontado",
            "item_exists": "Ya existe un elemento llamado \"%@\" en esta ubicación.",
            "create_folder_error": "Error al crear carpeta: %@",
            "create_file_error": "No se pudo crear el archivo.",
            "moved_to_trash_singular": "\"%@\" movido a la papelera",
            "moved_to_trash_plural": "%d elementos movidos a la papelera",
            "deleted_perm_singular": "\"%@\" eliminado permanentemente",
            "deleted_perm_plural": "%d elementos eliminados permanentemente",
            "compressing": "Comprimiendo \"%@\"...",
            "compress_success": "\"%@\" comprimido correctamente",
            "archive_name": "Nombre del Archivo",
            "format": "Formato",
            "compress_items": "Comprimir Ítems",
            "extracting": "Extrayendo \"%@\"...",
            "extract_success": "\"%@\" extraído correctamente",
            "renamed_to": "\"%@\" renombrado a \"%@\"",
            "copied_singular": "\"%@\" copiado",
            "copied_plural": "%d elementos copiados",
            "cut_singular": "\"%@\" cortado",
            "cut_plural": "%d elementos cortados",
            "pasting": "Pegando",
            "moving": "Moviendo",
            "pasting_singular": "%@ \"%@\"...",
            "pasting_plural": "%@ %d elementos...",
            "paste_success_singular": "\"%@\" %@ correctamente",
            "paste_success_plural": "%d elementos %@ correctamente",
            "no_tag_results": "No se encontraron elementos con esta etiqueta",
            "tag_added_singular": "Etiqueta \"%@\" añadida a \"%@\"",
            "tag_added_plural": "Etiqueta \"%@\" añadida a %d elementos",
            "tag_removed_singular": "Etiqueta \"%@\" eliminada de \"%@\"",
            "tag_removed_plural": "Etiqueta \"%@\" eliminada de %d elementos",
            "all_tags_removed_singular": "Etiquetas eliminadas de \"%@\"",
            "all_tags_removed_plural": "Etiquetas eliminadas de %d elementos",
            "added_to_favorites": "\"%@\" añadido a favoritos",
            "removed_from_favorites": "\"%@\" eliminado de favoritos",
            "no_items_found_for": "No se encontraron elementos para \"%@\"",
            "create": "Crear",
            "error_deleting_item": "Error al eliminar: %@",
            "pasted": "pegado",
            "moved": "movido",
            "folder_name_placeholder": "Nombre de la carpeta",
            "file_name_placeholder": "Nombre del archivo",
            "new_name_placeholder": "Nuevo nombre",
            "location": "Ubicación",
            "created": "Creado",
            "modified": "Modificado",
            "dimensions": "Dimensiones",
            "full_path": "Ruta completa",
            "contents": "Contenido",
            "close": "Cerrar",
            "folder": "Carpeta",
            "file": "Archivo",
            "calculating": "Calculando...",
            "ok": "OK",
            "access_denied_title": "Acceso denegado (protección de macOS)",
            "access_denied_message": "Para acceder a la Papelera o a carpetas protegidas del sistema, ve a:\nAjustes del Sistema > Privacidad y seguridad > Acceso total al disco\ny concede permiso a tu aplicación (o a Xcode/Terminal).",
            "access_error_generic": "No se pudo acceder a la carpeta.\nDetalles: %@",
            "replace": "Reemplazar",
            "keep_both": "Mantener ambos",
            "skip": "Omitir",
            "item_exists_title": "El elemento ya existe",
            "item_exists_message": "Ya existe un elemento llamado \"%@\" en esta ubicación. ¿Qué deseas hacer?",
            "rotate": "Rotar",
            "resize": "Redimensionar",
            "rotate_image": "Rotar imagen",
            "resize_image": "Redimensionar imagen",
            "rotation_angle": "Ángulo de rotación",
            "width": "Anchura",
            "height": "Altura",
            "maintain_aspect_ratio": "Mantener proporción",
            "apply": "Aplicar",
            "percent": "Porcentaje",
            "edit_dimension": "Dimensión base",
            "save_as_copy": "Guardar como copia",
            "name_label": "Nombre",
            "extension_label": "Extensión",
            "extension_warning": "Cambiar la extensión puede hacer que el archivo sea ilegible.",
            "unlock_extension_help": "Desbloquear extensión para editar",
            "lock_extension_help": "Bloquear extensión",
            "uppercase": "MAYÚSCULAS",
            "lowercase": "minúsculas",
            "capitalize": "Primera Letra en Mayúscula",
            "text_case_help": "Cambiar mayúsculas/minúsculas",
            "moved_singular": "\"%@\" movido a \"%@\"",
            "moved_plural": "%d elementos movidos a \"%@\"",
            "storage": "Almacenamiento",
            "storage_macintosh_hd": "Macintosh HD",
            "storage_total": "Capacidad total",
            "storage_used": "Utilizado",
            "storage_free": "Disponible",
            "storage_unavailable": "Información de almacenamiento no disponible",
        ]

        if lang == .es {
            return spanish[key] ?? dict[key]?[.en] ?? key
        }

        return dict[key]?[lang] ?? key
    }
}
